In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./dados_estação.csv', low_memory=False)

## Fazendo a primeira visualização dos dados
---

In [3]:
df

,Unnamed: 0,Estação,Mês,Mês.1,Dia,Hora,Ano,"Vel, Vento Máx, (Km/h)","Vel, Vento Média (Km/h)","Vel, Vento Vetor (Km/h)","Dir, Vento Média (graus)","Dir, Vento Desvio (graus)",Precipitação Total (mm),Temp. Ar Média (ºC),"Temp. Ar Máx, (ºC)",Temp. Ar Mínima (ºC),Um. Rel. Média (%),Um. Rel. Máxima (%),Um. Rel. Mínima (%)
0,0,Cerro do Roque,1,Janeiro,1.0,00:00:00,2020,"17,7","9,5","9,2","66,3","15,0","0,000","20,03","20,4","19,76","86,7","88,8","83,9"
1,1,Cerro do Roque,1,Janeiro,1.0,00:30:00,2020,"16,4","9,6","9,2","22,0","14,9","0,000",0,0,0,0,0,0
2,2,Cerro do Roque,1,Janeiro,1.0,01:00:00,2020,"17,3","11,2","10,8","15,0","14,7","0,000","20,48","20,98","19,96","81,5","86,6","76,81"
3,3,Cerro do Roque,1,Janeiro,1.0,01:30:00,2020,"17,0","9,0","8,8","4,0","13,6","0,000",0,0,0,0,0,0
4,4,Cerro do Roque,1,Janeiro,1.0,02:00:00,2020,"13,6","8,9","8,4","9,0","17,5","0,000","20,15","20,53","19,82","83,3","85,3","80,9"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470290,470290,Aroeira,12,dezembro,4.0,14:30:00,2023,"32,76","14,23","12,91","122,90","24,73","0,00","19,54","19,84","19,13","52,30","56,17","48,15"
470291,470291,Aroeira,12,dezembro,4.0,15:00:00,2023,"33,37","13,80","12,46","125,30","25,28","0,00","19,50","19,90","19,06","51,88","54,76","49,02"
470292,470292,Aroeira,12,dezembro,4.0,15:30:00,2023,"32,72","14,44","13,66","128,60","18,89","0,00","19,52","19,87","19,16","51,45","54,86","48,92"
470293,470293,Aroeira,12,dezembro,4.0,16:00:00,2023,"28,62","12,87","11,98","126,90","21,31","0,00","19,18","19,60","18,76","52,08","55,00","49,45"
470294,470294,Aroeira,12,dezembro,4.0,16:30:00,2023,"29,34","13,80","13,09","132,60","18,45","0,00","18,74","19,23","18,36","53,81","56,27","51,07"

In [4]:
print(len(df.columns))

19


## Visualizando os dados de cada coluna isoladamente, visando encontrar erros/outliers
---

In [5]:
for i in range(17):
    print(df.columns[i])
    print(df.iloc[:, i].unique())
    print()

Unnamed: 0
[     0      1      2 ... 470292 470293 470294]

Estação
['Cerro do Roque' 'Ramos' 'Terra Dura' 'Viveiro' 'São Sepé' 'São Manoel'
 'Aroeira']

Mês
[   1    2    3    4    7    8    9   10   11   12    5    6   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31 2023]

Mês.1
['Janeiro' 'Fevereiro' 'Março' 'Abril' 'Julho' 'Agosto' 'Setembro'
 'Outubro' 'Novembro' 'Dezembro' 'Maio' 'Junho ' 'abril' 'maio' 'junho'
 'julho' 'agosto' 'setembro' 'outubro' 'novembro' 'dezembro' 'janeiro'
 'fevereiro' 'março' 'Junho']

Dia
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. nan]

Hora
['00:00:00' '00:30:00' '01:00:00' '01:30:00' '02:00:00' '02:30:00'
 '03:00:00' '03:30:00' '04:00:00' '04:30:00' '05:00:00' '05:30:00'
 '06:00:00' '06:30:00' '07:00:00' '07:30:00' '08:00:00' '08:30:00'
 '09:00:00' '09:30:00' '10:00:00' '10:30:00' '11:00:00' '11:30:00'
 '12:00:00' '12:30:00' '13:00:00' '13:30:00' '14:00:00' '14:30:00'
 '15:00:00' '15:30:00' '16:00:00' '16:30:00' '17:00:00' '17:30:00'
 '18:00:00' '18:30:00' '19:00:00' '19:30:00' '20:00:00' '20:30:00'
 '21:00:00' '21:30:00' '22:00:00' '22:30:00' '23:00:00' '23:30:00' '00:00'
 '00:30' '01:00' '01:30' '02:00' '02:30' '03:00' '03:30' '04:00' '04:30'
 '05:00' '05:30' '06:00' '06:30' '07:00' '07:30' '08:00' '08:30' '09:00'
 '09:30' '10:00' '10:30' '11:00' '11:30' '12:00' '12:30' '13:00' '13:30'
 '14:00' '14:30' '15:00' '15:30' '16:00' '16:30' '17:00' '17:30' '18:00'
 '18:30' '19:00' '19:30' '20:00' '20:30' '21:00' '21:30' '22:00' '22:30'
 '23:00' '23:30' '0:00:00' '0:30:00' '1:00:00' '1:30:00' '2:00:00'
 '2:30:00' '3:00:00' '3:30:00' '4:00:00' '4:30:00' '5:00:00' '5:30:00'
 '6:00:00' '6:30:00' '7:00:00' '7:30:00' '8:00:00' '8:30:00' '9:00:00'
 '9:30:00']

Ano
['2020' '2021' '2022' '2023' nan '#REF!']

Vel, Vento Máx, (Km/h)
['17,7' '16,4' '17,3' ... '59,08' '70,96' '46,30']

Vel, Vento Média (Km/h)
['9,5' '9,6' '11,2' ... '21,65' '20,37' '24,70']

Vel, Vento Vetor (Km/h)
['9,2' '10,8' '8,8' ... '21,27' '21,38' '16,90']

Dir, Vento Média (graus)
['66,3' '22,0' '15,0' ... '62,83' '77,06' '40,32']

Dir, Vento Desvio (graus)
['15,0' '14,9' '14,7' ... '40,05' '53,00' '69,65']

Precipitação Total (mm)
['0,000' '0,254' '5,080' '9,400' '1,016' '2,794' '6,350' '16,510' '1,270'
 '1,524' '4,318' '3,302' '2,032' '0,508' '0,762' '8,130' '16,760' '13,210'
 '1,778' '2,286' '10,920' '2,540' '3,810' '4,826' '4,064' '10,160' '3,048'
 '4,572' '22,610' '8,890' '6,096' '7,874' '3,556' '8,380' '17,020' '6,604'
 '11,940' '35,050' '9,140' '10,410' '5,334' '19,050' '7,620' '12,190'
 '5,588' '9,650' '6,858' '9,910' '13,460' '5,842' '7,366' '8,640' '11,180'
 '0' '0,0' '6,4' '3,3' '1,3' '0,3' '0,5' '21,3' '0,8' '4,6' '1,5' '1,0'
 '7,6' '16,5' '3,8' '2,5' '2,8' '5,8' '3,0' '3,6' '1,8' '4,1' '9,7' '10,7'
 '5,1' '2,3' nan '15,0' '2,0' '8,1' '5,3' '10,9' '5,6' '9,9' '7,9' '4,8'
 '8,4' '13,2' '6,1' '7,4' '4,3' '12,2' '6,6' '12,7' '10,4' '8,6' '11,9'
 '11,4' '10,2' '13,0' '11,2' '11,7' '17,8' '33,5' '9,1' '7,1' '0,25'
 '0,00' '1,02' '2,79' '1,78' '8,64' '0,51' '1,52' '5,84' '1,27' '0,76'
 '2,03' '3,56' '5,33' '5,59' '4,06' '2,29' '3,81' '6,60' '2,54' '3,05'
 '3,30' '25,91' '4,57' '10,92' '6,35' '4,32' '9,4' '14,7' '12,450'
 '10,670' '14,220' '11,680' '7,112' '14,990' '12,700' '14,480' '19,300'
 '14,730' '12,950' '19,1' '14,2' '13,5' '20,1' '18,0' '19,8' '14,5' '39,9'
 '6,9' '24,9' '34,0' '14,0' '15,8' '15,2' '16,0' '18,8' '8,9' '22,1'
 '24,640' '15,240' '17,780' '11,430' '17,270' '20,570' '18,5' '40,1'
 '20,8' '4,83' '7,11' '8,13' '20,83' '6,86' '17,27' '6,10' '5,08' '8,38'
 '9,40' '7,37' '7,62' '17,02' '15,750' '13,970' '35,8' '23,9' '17,0'
 '38,4' '12,5' '24,1' '0,20' '0,40' '0,80' '2,00' '0,60' '1,00' '2,80'
 '1,20' '7,40' '2,40' '1,40' '3,60' '4,20' '3,40' '2,60' '1,80' '1,60'
 '5,00' '5,20' '4,40' '19,20' '6,20' '4,00' '3,20' '7,60' '3,80' '6,00'
 '2,20' '3,00' '5,80' '8,40' '8,80' '7,20' '4,80' '11,80' '13,60' '11,18'
 '10,16' '9,14' '8,89' '14,22' '19,810' '34,5' '53,3' '23,1' '22,9' '15,5'
 '12,95' '10,67' '7,87' '9,65' '18,54' '16,26' '12,70' '16,000' '20,830'
 '26,920' '16,76' '9,91' '17,3' '28,7' '19,3' '21,6' '16,8' '13,720'
 '21,340' '21,1' '32,5' '30,0' '13,97' '11,68' '10,41' '17,78' '12,19']

Temp. Ar Média (ºC)
['20,03' '0' '20,48' ... '33,55' '32,47' '32,20']

Temp. Ar Máx, (ºC)
['20,4' '0' '20,98' ... '34,39' '34,05' '32,78']

Temp. Ar  Mínima (ºC)
['19,76' '0' '19,96' ... '30,21' '30,91' '33,02']

Um. Rel. Média (%)
['86,7' '0' '81,5' ... '39,98' '39,30' '46,84']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470295 entries, 0 to 470294
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Unnamed: 0                 470295 non-null  int64
 1   Estação                    470295 non-null  object
 2   Mês                        470295 non-null  int64
 3   Mês.1                      470295 non-null  object
 4   Dia                        470284 non-null  float64
 5   Hora                       470295 non-null  object
 6   Ano                        470273 non-null  object
 7   Vel, Vento Máx, (Km/h)     464082 non-null  object
 8   Vel, Vento Média (Km/h)    466038 non-null  object
 9   Vel, Vento Vetor (Km/h)    457185 non-null  object
 10  Dir, Vento Média (graus)   465590 non-null  object
 11  Dir, Vento Desvio (graus)  459505 non-null  object
 12  Precipitação Total (mm)    466224 non-null  object
 13  Temp. Ar Média (ºC)        443210 non-null  object
 14  Temp. Ar Máx, (ºC)         443969 non-null  object
 15  Temp. Ar  Mínima (ºC)      443923 non-null  object
 16  Um. Rel. Média (%)         443406 non-null  object
 17  Um. Rel. Máxima (%)        443422 non-null  object
 18  Um. Rel. Mínima (%)        443407 non-null  object
dtypes: float64(1), int64(2), object(16)
memory usage: 68.2+ MB

<br> <br>

## Corrigindo os dados da coluna "Mês"
---

In [7]:
df.drop(columns=['Unnamed: 0', 'Mês'], inplace=True)

In [8]:
df.loc[:,'Mês.1'].replace(to_replace='janeiro', value='Janeiro', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='fevereiro', value='Fevereiro', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='março', value='Março', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='abril', value='Abril', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='maio', value='Maio', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='junho', value='Junho', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='julho', value='Julho', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='agosto', value='Agosto', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='setembro', value='Setembro', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='outubro', value='Outubro', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='novembro', value='Novembro', inplace=True)
df.loc[:,'Mês.1'].replace(to_replace='dezembro', value='Dezembro', inplace=True)

<br> <br>

## Corrigindo os problemas da coluna "Dia"
---

In [9]:
df = df.loc[~df['Dia'].isna(), :]

In [10]:
df['Dia'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31.])

In [11]:
corretos = ['00:00:00','00:30:00','01:00:00','01:30:00','02:00:00','02:30:00',
            '03:00:00','03:30:00','04:00:00','04:30:00','05:00:00','05:30:00',
            '06:00:00','06:30:00','07:00:00','07:30:00','08:00:00','08:30:00',
            '09:00:00','09:30:00','10:00:00','10:30:00','11:00:00','11:30:00',
            '12:00:00','12:30:00','13:00:00','13:30:00','14:00:00','14:30:00',
            '15:00:00','15:30:00','16:00:00','16:30:00','17:00:00','17:30:00',
            '18:00:00','18:30:00','19:00:00','19:30:00','20:00:00','20:30:00',
            '21:00:00','21:30:00','22:00:00','22:30:00','23:00:00','23:30:00',
            '00:00:00','00:30:00','01:00:00','01:30:00','02:00:00','02:30:00',
            '03:00:00','03:30:00','04:00:00','04:30:00','05:00:00','05:30:00',
            '06:00:00','06:30:00','07:00:00','07:30:00','08:00:00','08:30:00',
            '09:00:00','09:30:00']

incorretos = ['00:00','00:30','01:00','01:30','02:00','02:30',
              '03:00','03:30','04:00','04:30','05:00','05:30',
              '06:00','06:30','07:00','07:30','08:00','08:30',
              '09:00','09:30','10:00','10:30','11:00','11:30',
              '12:00','12:30','13:00','13:30','14:00','14:30',
              '15:00','15:30','16:00','16:30','17:00','17:30',
              '18:00','18:30','19:00','19:30','20:00','20:30',
              '21:00','21:30','22:00','22:30','23:00','23:30',
              '0:00:00','0:30:00','1:00:00','1:30:00','2:00:00',
              '2:30:00','3:00:00','3:30:00','4:00:00','4:30:00',
              '5:00:00','5:30:00','6:00:00','6:30:00','7:00:00',
              '7:30:00','8:00:00','8:30:00','9:00:00','9:30:00']

In [12]:
for i in range(len(incorretos)):
    df.loc[:, 'Hora'].replace(to_replace=incorretos[i], value=corretos[i], inplace=True)

C:\Users\edmar\AppData\Local\Temp\ipykernel_4228\2050492939.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'Hora'].replace(to_replace=incorretos[i], value=corretos[i], inplace=True)

<br> <br>

## Corrigindo dados da coluna "Ano"
---

In [13]:
df.loc[:, 'Ano'].unique()

array(['2020', '2021', '2022', '2023', nan, '#REF!'], dtype=object)

In [14]:
df.replace(to_replace='#REF!', value='2020', inplace=True)

C:\Users\edmar\AppData\Local\Temp\ipykernel_4228\4227805675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace(to_replace='#REF!', value='2020', inplace=True)

In [15]:
df[df['Ano'].isna()]

,Estação,Mês.1,Dia,Hora,Ano,"Vel, Vento Máx, (Km/h)","Vel, Vento Média (Km/h)","Vel, Vento Vetor (Km/h)","Dir, Vento Média (graus)","Dir, Vento Desvio (graus)",Precipitação Total (mm),Temp. Ar Média (ºC),"Temp. Ar Máx, (ºC)",Temp. Ar Mínima (ºC),Um. Rel. Média (%),Um. Rel. Máxima (%),Um. Rel. Mínima (%)
109261,Ramos,Maio,28.0,23:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109262,Ramos,Maio,29.0,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109263,Ramos,Maio,29.0,00:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109264,Ramos,Maio,29.0,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109265,Ramos,Maio,29.0,01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109266,Ramos,Maio,29.0,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109267,Ramos,Maio,29.0,02:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109268,Ramos,Maio,29.0,03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109269,Ramos,Maio,29.0,03:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109270,Ramos,Maio,29.0,04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109271,Ramos,Maio,29.0,04:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109272,Ramos,Maio,29.0,05:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109273,Ramos,Maio,29.0,05:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109274,Ramos,Maio,29.0,06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109275,Ramos,Maio,29.0,06:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109276,Ramos,Maio,29.0,07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109277,Ramos,Maio,29.0,07:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109278,Ramos,Maio,29.0,08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109279,Ramos,Maio,29.0,08:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109280,Ramos,Maio,29.0,09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109281,Ramos,Maio,29.0,09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109282,Ramos,Maio,29.0,10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.loc[~df['Ano'].isna(), :]

In [17]:
df

,Estação,Mês.1,Dia,Hora,Ano,"Vel, Vento Máx, (Km/h)","Vel, Vento Média (Km/h)","Vel, Vento Vetor (Km/h)","Dir, Vento Média (graus)","Dir, Vento Desvio (graus)",Precipitação Total (mm),Temp. Ar Média (ºC),"Temp. Ar Máx, (ºC)",Temp. Ar Mínima (ºC),Um. Rel. Média (%),Um. Rel. Máxima (%),Um. Rel. Mínima (%)
0,Cerro do Roque,Janeiro,1.0,00:00:00,2020,"17,7","9,5","9,2","66,3","15,0","0,000","20,03","20,4","19,76","86,7","88,8","83,9"
1,Cerro do Roque,Janeiro,1.0,00:30:00,2020,"16,4","9,6","9,2","22,0","14,9","0,000",0,0,0,0,0,0
2,Cerro do Roque,Janeiro,1.0,01:00:00,2020,"17,3","11,2","10,8","15,0","14,7","0,000","20,48","20,98","19,96","81,5","86,6","76,81"
3,Cerro do Roque,Janeiro,1.0,01:30:00,2020,"17,0","9,0","8,8","4,0","13,6","0,000",0,0,0,0,0,0
4,Cerro do Roque,Janeiro,1.0,02:00:00,2020,"13,6","8,9","8,4","9,0","17,5","0,000","20,15","20,53","19,82","83,3","85,3","80,9"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470290,Aroeira,Dezembro,4.0,14:30:00,2023,"32,76","14,23","12,91","122,90","24,73","0,00","19,54","19,84","19,13","52,30","56,17","48,15"
470291,Aroeira,Dezembro,4.0,15:00:00,2023,"33,37","13,80","12,46","125,30","25,28","0,00","19,50","19,90","19,06","51,88","54,76","49,02"
470292,Aroeira,Dezembro,4.0,15:30:00,2023,"32,72","14,44","13,66","128,60","18,89","0,00","19,52","19,87","19,16","51,45","54,86","48,92"
470293,Aroeira,Dezembro,4.0,16:00:00,2023,"28,62","12,87","11,98","126,90","21,31","0,00","19,18","19,60","18,76","52,08","55,00","49,45"
470294,Aroeira,Dezembro,4.0,16:30:00,2023,"29,34","13,80","13,09","132,60","18,45","0,00","18,74","19,23","18,36","53,81","56,27","51,07"

<br> <br>

## Corrigindo os problemas da coluna "Precipitação Total (mm)"
---

In [18]:
df['Precipitação Total (mm)'].unique()

array(['0,000', '0,254', '5,080', '9,400', '1,016', '2,794', '6,350',
       '16,510', '1,270', '1,524', '4,318', '3,302', '2,032', '0,508',
       '0,762', '8,130', '16,760', '13,210', '1,778', '2,286', '10,920',
       '2,540', '3,810', '4,826', '4,064', '10,160', '3,048', '4,572',
       '22,610', '8,890', '6,096', '7,874', '3,556', '8,380', '17,020',
       '6,604', '11,940', '35,050', '9,140', '10,410', '5,334', '19,050',
       '7,620', '12,190', '5,588', '9,650', '6,858', '9,910', '13,460',
       '5,842', '7,366', '8,640', '11,180', '0', '0,0', '6,4', '3,3',
       '1,3', '0,3', '0,5', '21,3', '0,8', '4,6', '1,5', '1,0', '7,6',
       '16,5', '3,8', '2,5', '2,8', '5,8', '3,0', '3,6', '1,8', '4,1',
       '9,7', '10,7', '5,1', '2,3', nan, '15,0', '2,0', '8,1', '5,3',
       '10,9', '5,6', '9,9', '7,9', '4,8', '8,4', '13,2', '6,1', '7,4',
       '4,3', '12,2', '6,6', '12,7', '10,4', '8,6', '11,9', '11,4',
       '10,2', '13,0', '11,2', '11,7', '17,8', '33,5', '9,1', '7,1',
       '0,25', '0,00', '1,02', '2,79', '1,78', '8,64', '0,51', '1,52',
       '5,84', '1,27', '0,76', '2,03', '3,56', '5,33', '5,59', '4,06',
       '2,29', '3,81', '6,60', '2,54', '3,05', '3,30', '25,91', '4,57',
       '10,92', '6,35', '4,32', '9,4', '14,7', '12,450', '10,670',
       '14,220', '11,680', '7,112', '14,990', '12,700', '14,480',
       '19,300', '14,730', '12,950', '19,1', '14,2', '13,5', '20,1',
       '18,0', '19,8', '14,5', '39,9', '6,9', '24,9', '34,0', '14,0',
       '15,8', '15,2', '16,0', '18,8', '8,9', '22,1', '24,640', '15,240',
       '17,780', '11,430', '17,270', '20,570', '18,5', '40,1', '20,8',
       '4,83', '7,11', '8,13', '20,83', '6,86', '17,27', '6,10', '5,08',
       '8,38', '9,40', '7,37', '7,62', '17,02', '15,750', '13,970',
       '35,8', '23,9', '17,0', '38,4', '12,5', '24,1', '0,20', '0,40',
       '0,80', '2,00', '0,60', '1,00', '2,80', '1,20', '7,40', '2,40',
       '1,40', '3,60', '4,20', '3,40', '2,60', '1,80', '1,60', '5,00',
       '5,20', '4,40', '19,20', '6,20', '4,00', '3,20', '7,60', '3,80',
       '6,00', '2,20', '3,00', '5,80', '8,40', '8,80', '7,20', '4,80',
       '11,80', '13,60', '11,18', '10,16', '9,14', '8,89', '14,22',
       '19,810', '34,5', '53,3', '23,1', '22,9', '15,5', '12,95', '10,67',
       '7,87', '9,65', '18,54', '16,26', '12,70', '16,000', '20,830',
       '26,920', '16,76', '9,91', '17,3', '28,7', '19,3', '21,6', '16,8',
       '13,720', '21,340', '21,1', '32,5', '30,0', '13,97', '11,68',
       '10,41', '17,78', '12,19'], dtype=object)

In [19]:
df = df.loc[~df['Precipitação Total (mm)'].isna(), :]

In [20]:
df['Precipitação Total (mm)'].unique()

array(['0,000', '0,254', '5,080', '9,400', '1,016', '2,794', '6,350',
       '16,510', '1,270', '1,524', '4,318', '3,302', '2,032', '0,508',
       '0,762', '8,130', '16,760', '13,210', '1,778', '2,286', '10,920',
       '2,540', '3,810', '4,826', '4,064', '10,160', '3,048', '4,572',
       '22,610', '8,890', '6,096', '7,874', '3,556', '8,380', '17,020',
       '6,604', '11,940', '35,050', '9,140', '10,410', '5,334', '19,050',
       '7,620', '12,190', '5,588', '9,650', '6,858', '9,910', '13,460',
       '5,842', '7,366', '8,640', '11,180', '0', '0,0', '6,4', '3,3',
       '1,3', '0,3', '0,5', '21,3', '0,8', '4,6', '1,5', '1,0', '7,6',
       '16,5', '3,8', '2,5', '2,8', '5,8', '3,0', '3,6', '1,8', '4,1',
       '9,7', '10,7', '5,1', '2,3', '15,0', '2,0', '8,1', '5,3', '10,9',
       '5,6', '9,9', '7,9', '4,8', '8,4', '13,2', '6,1', '7,4', '4,3',
       '12,2', '6,6', '12,7', '10,4', '8,6', '11,9', '11,4', '10,2',
       '13,0', '11,2', '11,7', '17,8', '33,5', '9,1', '7,1', '0,25',
       '0,00', '1,02', '2,79', '1,78', '8,64', '0,51', '1,52', '5,84',
       '1,27', '0,76', '2,03', '3,56', '5,33', '5,59', '4,06', '2,29',
       '3,81', '6,60', '2,54', '3,05', '3,30', '25,91', '4,57', '10,92',
       '6,35', '4,32', '9,4', '14,7', '12,450', '10,670', '14,220',
       '11,680', '7,112', '14,990', '12,700', '14,480', '19,300',
       '14,730', '12,950', '19,1', '14,2', '13,5', '20,1', '18,0', '19,8',
       '14,5', '39,9', '6,9', '24,9', '34,0', '14,0', '15,8', '15,2',
       '16,0', '18,8', '8,9', '22,1', '24,640', '15,240', '17,780',
       '11,430', '17,270', '20,570', '18,5', '40,1', '20,8', '4,83',
       '7,11', '8,13', '20,83', '6,86', '17,27', '6,10', '5,08', '8,38',
       '9,40', '7,37', '7,62', '17,02', '15,750', '13,970', '35,8',
       '23,9', '17,0', '38,4', '12,5', '24,1', '0,20', '0,40', '0,80',
       '2,00', '0,60', '1,00', '2,80', '1,20', '7,40', '2,40', '1,40',
       '3,60', '4,20', '3,40', '2,60', '1,80', '1,60', '5,00', '5,20',
       '4,40', '19,20', '6,20', '4,00', '3,20', '7,60', '3,80', '6,00',
       '2,20', '3,00', '5,80', '8,40', '8,80', '7,20', '4,80', '11,80',
       '13,60', '11,18', '10,16', '9,14', '8,89', '14,22', '19,810',
       '34,5', '53,3', '23,1', '22,9', '15,5', '12,95', '10,67', '7,87',
       '9,65', '18,54', '16,26', '12,70', '16,000', '20,830', '26,920',
       '16,76', '9,91', '17,3', '28,7', '19,3', '21,6', '16,8', '13,720',
       '21,340', '21,1', '32,5', '30,0', '13,97', '11,68', '10,41',
       '17,78', '12,19'], dtype=object)

<br> <br>

## Corrigindo os problemas da coluna "Temp. Ar Média (ºC)"
---
<br>

In [21]:
df['Temp. Ar Média (ºC)'].dropna()

0         20,03
1             0
2         20,48
3             0
4         20,15
          ...
470290    19,54
470291    19,50
470292    19,52
470293    19,18
470294    18,74
Name: Temp. Ar Média (ºC), Length: 443194, dtype: object

In [22]:
df = df.dropna()

<br> <br>
## Corrigindo os problemas da coluna "Vel, Vento Máx, Média e Vetor (Km/h)"
---
<br>

In [23]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 20)

In [24]:
df.loc[:, "Vel, Vento Máx, (Km/h)"].replace(to_replace=",",value=".", regex=True, inplace=True)

In [25]:
df["Vel, Vento Máx, (Km/h)"] = df["Vel, Vento Máx, (Km/h)"].astype(float)

In [26]:
df["Vel, Vento Máx, (Km/h)"]

0         17.70
1         16.40
2         17.30
3         17.00
4         13.60
          ...
470290    32.76
470291    33.37
470292    32.72
470293    28.62
470294    29.34
Name: Vel, Vento Máx, (Km/h), Length: 432358, dtype: float64

In [27]:
df.loc[:, "Vel, Vento Média (Km/h)"].replace(to_replace=",",value=".", regex=True, inplace=True)

In [28]:
df["Vel, Vento Média (Km/h)"] = df["Vel, Vento Média (Km/h)"].astype(float)

In [29]:
df["Vel, Vento Média (Km/h)"]

0          9.50
1          9.60
2         11.20
3          9.00
4          8.90
          ...
470290    14.23
470291    13.80
470292    14.44
470293    12.87
470294    13.80
Name: Vel, Vento Média (Km/h), Length: 432358, dtype: float64

In [30]:
df.loc[:, "Vel, Vento Vetor (Km/h)"].replace(to_replace=",",value=".", regex=True, inplace=True)

In [31]:
df["Vel, Vento Vetor (Km/h)"] = df["Vel, Vento Vetor (Km/h)"].astype(float)

In [32]:
df["Vel, Vento Vetor (Km/h)"]

0          9.20
1          9.20
2         10.80
3          8.80
4          8.40
          ...
470290    12.91
470291    12.46
470292    13.66
470293    11.98
470294    13.09
Name: Vel, Vento Vetor (Km/h), Length: 432358, dtype: float64

<br> <br>
## Corrigindo os problemas da coluna "Dir, Vento Média e Desvios (graus)"
---
<br>

In [33]:
df.loc[:, "Dir, Vento Média (graus)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Dir, Vento Média (graus)"] = df["Dir, Vento Média (graus)"].astype(float)

In [34]:
df["Vel, Vento Vetor (Km/h)"]

0          9.20
1          9.20
2         10.80
3          8.80
4          8.40
          ...
470290    12.91
470291    12.46
470292    13.66
470293    11.98
470294    13.09
Name: Vel, Vento Vetor (Km/h), Length: 432358, dtype: float64

In [35]:
df.loc[:, "Dir, Vento Desvio (graus)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Dir, Vento Desvio (graus)"] = df["Dir, Vento Desvio (graus)"].astype(float)

In [36]:
df["Dir, Vento Desvio (graus)"]

0         15.00
1         14.90
2         14.70
3         13.60
4         17.50
          ...
470290    24.73
470291    25.28
470292    18.89
470293    21.31
470294    18.45
Name: Dir, Vento Desvio (graus), Length: 432358, dtype: float64

<br> <br>
## Corrigindo os problemas da coluna "Temp. Ar Média, Máxima e Mínima (ºC)"
---
<br>

In [37]:
df.loc[:, "Temp. Ar Média (ºC)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Temp. Ar Média (ºC)"] = df["Temp. Ar Média (ºC)"].astype(float)

In [38]:
df["Temp. Ar Média (ºC)"]

0         20.03
1          0.00
2         20.48
3          0.00
4         20.15
          ...
470290    19.54
470291    19.50
470292    19.52
470293    19.18
470294    18.74
Name: Temp. Ar Média (ºC), Length: 432358, dtype: float64

In [39]:
df.loc[:, "Temp. Ar Máx, (ºC)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Temp. Ar Máx, (ºC)"] = df["Temp. Ar Máx, (ºC)"].astype(float)

In [40]:
df["Temp. Ar Máx, (ºC)"]

0         20.40
1          0.00
2         20.98
3          0.00
4         20.53
          ...
470290    19.84
470291    19.90
470292    19.87
470293    19.60
470294    19.23
Name: Temp. Ar Máx, (ºC), Length: 432358, dtype: float64

In [41]:
df.loc[:, "Temp. Ar  Mínima (ºC)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Temp. Ar  Mínima (ºC)"] = df["Temp. Ar  Mínima (ºC)"].astype(float)

In [42]:
df["Temp. Ar  Mínima (ºC)"]

0         19.76
1          0.00
2         19.96
3          0.00
4         19.82
          ...
470290    19.13
470291    19.06
470292    19.16
470293    18.76
470294    18.36
Name: Temp. Ar  Mínima (ºC), Length: 432358, dtype: float64

<br> <br>
## Corrigindo os problemas da coluna "Um. Rel. Média, Máxima e Mínima (%)"
---
<br>

In [43]:
df.loc[:, "Um. Rel. Média (%)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Um. Rel. Média (%)"] = df["Um. Rel. Média (%)"].astype(float)

In [44]:
df["Um. Rel. Média (%)"]

0         86.70
1          0.00
2         81.50
3          0.00
4         83.30
          ...
470290    52.30
470291    51.88
470292    51.45
470293    52.08
470294    53.81
Name: Um. Rel. Média (%), Length: 432358, dtype: float64

In [45]:
df.loc[:, "Um. Rel. Máxima (%)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Um. Rel. Máxima (%)"] = df["Um. Rel. Máxima (%)"].astype(float)

In [46]:
df["Um. Rel. Máxima (%)"]

0         88.80
1          0.00
2         86.60
3          0.00
4         85.30
          ...
470290    56.17
470291    54.76
470292    54.86
470293    55.00
470294    56.27
Name: Um. Rel. Máxima (%), Length: 432358, dtype: float64

In [47]:
df.loc[:, "Um. Rel. Mínima (%)"].replace(to_replace=",",value=".", regex=True, inplace=True)
df["Um. Rel. Mínima (%)"] = df["Um. Rel. Mínima (%)"].astype(float)

In [48]:
df["Um. Rel. Mínima (%)"]

0         83.90
1          0.00
2         76.81
3          0.00
4         80.90
          ...
470290    48.15
470291    49.02
470292    48.92
470293    49.45
470294    51.07
Name: Um. Rel. Mínima (%), Length: 432358, dtype: float64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 432358 entries, 0 to 470294
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Estação                    432358 non-null  object
 1   Mês.1                      432358 non-null  object
 2   Dia                        432358 non-null  float64
 3   Hora                       432358 non-null  object
 4   Ano                        432358 non-null  object
 5   Vel, Vento Máx, (Km/h)     432358 non-null  float64
 6   Vel, Vento Média (Km/h)    432189 non-null  float64
 7   Vel, Vento Vetor (Km/h)    432096 non-null  float64
 8   Dir, Vento Média (graus)   432358 non-null  float64
 9   Dir, Vento Desvio (graus)  432358 non-null  float64
 10  Precipitação Total (mm)    432358 non-null  object
 11  Temp. Ar Média (ºC)        431686 non-null  float64
 12  Temp. Ar Máx, (ºC)         431687 non-null  float64
 13  Temp. Ar  Mínima (ºC)      431687 non-null  float64
 14  Um. Rel. Média (%)         432357 non-null  float64
 15  Um. Rel. Máxima (%)        432358 non-null  float64
 16  Um. Rel. Mínima (%)        432358 non-null  float64
dtypes: float64(12), object(5)
memory usage: 59.4+ MB

In [50]:
df.describe().iloc[0,:]

Dia                          432358.0
Vel, Vento Máx, (Km/h)       432358.0
Vel, Vento Média (Km/h)      432189.0
Vel, Vento Vetor (Km/h)      432096.0
Dir, Vento Média (graus)     432358.0
Dir, Vento Desvio (graus)    432358.0
Temp. Ar Média (ºC)          431686.0
Temp. Ar Máx, (ºC)           431687.0
Temp. Ar  Mínima (ºC)        431687.0
Um. Rel. Média (%)           432357.0
Um. Rel. Máxima (%)          432358.0
Um. Rel. Mínima (%)          432358.0
Name: count, dtype: float64

In [51]:
df.describe().iloc[0,:].max() - df.describe().iloc[0,:].min()

672.0

In [52]:
df.head(15)

,Estação,Mês.1,Dia,Hora,Ano,"Vel, Vento Máx, (Km/h)","Vel, Vento Média (Km/h)","Vel, Vento Vetor (Km/h)","Dir, Vento Média (graus)","Dir, Vento Desvio (graus)",Precipitação Total (mm),Temp. Ar Média (ºC),"Temp. Ar Máx, (ºC)",Temp. Ar Mínima (ºC),Um. Rel. Média (%),Um. Rel. Máxima (%),Um. Rel. Mínima (%)
0,Cerro do Roque,Janeiro,1.0,00:00:00,2020,17.7,9.5,9.2,66.3,15.0,"0,000",20.03,20.40,19.76,86.7,88.8,83.90
1,Cerro do Roque,Janeiro,1.0,00:30:00,2020,16.4,9.6,9.2,22.0,14.9,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
2,Cerro do Roque,Janeiro,1.0,01:00:00,2020,17.3,11.2,10.8,15.0,14.7,"0,000",20.48,20.98,19.96,81.5,86.6,76.81
3,Cerro do Roque,Janeiro,1.0,01:30:00,2020,17.0,9.0,8.8,4.0,13.6,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
4,Cerro do Roque,Janeiro,1.0,02:00:00,2020,13.6,8.9,8.4,9.0,17.5,"0,000",20.15,20.53,19.82,83.3,85.3,80.90
5,Cerro do Roque,Janeiro,1.0,02:30:00,2020,12.4,6.7,6.4,334.7,17.2,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
6,Cerro do Roque,Janeiro,1.0,03:00:00,2020,10.9,6.3,6.2,323.6,13.2,"0,000",20.24,20.47,20.00,83.7,85.1,81.90
7,Cerro do Roque,Janeiro,1.0,03:30:00,2020,12.0,7.3,7.2,312.9,12.5,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
8,Cerro do Roque,Janeiro,1.0,04:00:00,2020,12.1,8.3,8.0,297.8,15.6,"0,000",20.43,20.81,20.13,83.7,84.8,81.80
9,Cerro do Roque,Janeiro,1.0,04:30:00,2020,11.8,7.9,7.7,286.9,10.2,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
10,Cerro do Roque,Janeiro,1.0,05:00:00,2020,14.6,10.4,10.3,301.2,6.4,"0,000",20.51,20.71,20.06,83.4,84.9,82.30
11,Cerro do Roque,Janeiro,1.0,05:30:00,2020,13.9,10.4,10.4,303.3,3.8,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
12,Cerro do Roque,Janeiro,1.0,06:00:00,2020,13.8,10.8,10.8,301.8,3.8,"0,000",20.40,20.63,20.16,84.2,84.8,83.10
13,Cerro do Roque,Janeiro,1.0,06:30:00,2020,15.2,12.2,12.1,304.4,6.1,"0,000",0.00,0.00,0.00,0.0,0.0,0.00
14,Cerro do Roque,Janeiro,1.0,07:00:00,2020,18.4,13.7,13.7,308.9,4.3,"0,000",20.42,20.66,20.26,84.5,84.8,84.10

<br> <br>
### Removendo as colunas de direção do vento (graus), temperaturas extremas (máximo e mínimo), velocidade do vento extremas (máximo e mínimo) e umidades relativas extremas (máximo e mínimo).
---

In [53]:
df.drop(columns=["Dir, Vento Média (graus)", "Dir, Vento Desvio (graus)", "Vel, Vento Máx, (Km/h)", "Vel, Vento Vetor (Km/h)", "Temp. Ar  Mínima (ºC)", "Temp. Ar Máx, (ºC)", "Um. Rel. Máxima (%)", "Um. Rel. Mínima (%)"], inplace=True)

<br> <br>
### Removendo todos os registros (instâncias) das horas intermediárias (00:30:00, 01:30:00, 02:30:00, 03:30:00, ..., 23:30:00) pois nesses horários as bases não registraram dados de temperatura, precipitação e umidade relativa.
---

In [54]:
verif = df['Hora'].str.contains('30')
df = df[~verif]
df.reset_index(drop=True, inplace=True)

In [55]:
df

,Estação,Mês.1,Dia,Hora,Ano,"Vel, Vento Média (Km/h)",Precipitação Total (mm),Temp. Ar Média (ºC),Um. Rel. Média (%)
0,Cerro do Roque,Janeiro,1.0,00:00:00,2020,9.50,"0,000",20.03,86.70
1,Cerro do Roque,Janeiro,1.0,01:00:00,2020,11.20,"0,000",20.48,81.50
2,Cerro do Roque,Janeiro,1.0,02:00:00,2020,8.90,"0,000",20.15,83.30
3,Cerro do Roque,Janeiro,1.0,03:00:00,2020,6.30,"0,000",20.24,83.70
4,Cerro do Roque,Janeiro,1.0,04:00:00,2020,8.30,"0,000",20.43,83.70
...,...,...,...,...,...,...,...,...,...
218547,Aroeira,Dezembro,4.0,12:00:00,2023,15.54,"0,00",18.31,58.94
218548,Aroeira,Dezembro,4.0,13:00:00,2023,15.42,"0,00",18.77,56.25
218549,Aroeira,Dezembro,4.0,14:00:00,2023,14.56,"0,00",19.25,52.84
218550,Aroeira,Dezembro,4.0,15:00:00,2023,13.80,"0,00",19.50,51.88
218551,Aroeira,Dezembro,4.0,16:00:00,2023,12.87,"0,00",19.18,52.08

<br> <br>
# Definindo as Condições para Aplicação
---
### 1. Temperatura Média do Ar (°C):

* Ideal: **30 >= X >= 20**
* Possível: **5 <= X < 20**
* Impróprio: **5 > X > 30**

### 2. Velocidade Média do Vento (km/h):

* Ideal: **X <= 5**
* Possível: **5 < X <= 10**
* Impróprio: **X > 10**

### 3. Umidade Relativa do Ar (%):

* Ideal: **X >= 60**
* Possível: **50 <= X < 60**
* Impróprio: **X < 50**
<br>

In [56]:
def avaliador_temp(registro):
  if registro <= 30 and registro >= 20:
    return "Ideal"
  elif registro >= 5:
    return "Possível"
  else:
    return "Impróprio"

def avaliador_vento(registro):
  if registro <= 5:
    return "Ideal"
  elif registro <= 10:
    return "Possível"
  else:
    return "Impróprio"

def avaliador_umidade(registro):
  if registro >= 60:
    return "Ideal"
  elif registro >= 50:
    return "Possível"
  else:
    return "Impróprio"

def print_full(x):
  pd.set_option('display.max_rows', len(x))
  print(x)
  pd.reset_option('display.max_rows')

In [57]:
df

,Estação,Mês.1,Dia,Hora,Ano,"Vel, Vento Média (Km/h)",Precipitação Total (mm),Temp. Ar Média (ºC),Um. Rel. Média (%)
0,Cerro do Roque,Janeiro,1.0,00:00:00,2020,9.50,"0,000",20.03,86.70
1,Cerro do Roque,Janeiro,1.0,01:00:00,2020,11.20,"0,000",20.48,81.50
2,Cerro do Roque,Janeiro,1.0,02:00:00,2020,8.90,"0,000",20.15,83.30
3,Cerro do Roque,Janeiro,1.0,03:00:00,2020,6.30,"0,000",20.24,83.70
4,Cerro do Roque,Janeiro,1.0,04:00:00,2020,8.30,"0,000",20.43,83.70
...,...,...,...,...,...,...,...,...,...
218547,Aroeira,Dezembro,4.0,12:00:00,2023,15.54,"0,00",18.31,58.94
218548,Aroeira,Dezembro,4.0,13:00:00,2023,15.42,"0,00",18.77,56.25
218549,Aroeira,Dezembro,4.0,14:00:00,2023,14.56,"0,00",19.25,52.84
218550,Aroeira,Dezembro,4.0,15:00:00,2023,13.80,"0,00",19.50,51.88
218551,Aroeira,Dezembro,4.0,16:00:00,2023,12.87,"0,00",19.18,52.08

In [58]:
df.columns

Index(['Estação', 'Mês.1', 'Dia', 'Hora', 'Ano', 'Vel, Vento Média (Km/h)',
       'Precipitação Total (mm)', 'Temp. Ar Média (ºC)', 'Um. Rel. Média (%)'],
      dtype='object')

In [59]:
df.rename(columns={'Mês.1':'Mês'}, inplace=True)

In [60]:
df

,Estação,Mês,Dia,Hora,Ano,"Vel, Vento Média (Km/h)",Precipitação Total (mm),Temp. Ar Média (ºC),Um. Rel. Média (%)
0,Cerro do Roque,Janeiro,1.0,00:00:00,2020,9.50,"0,000",20.03,86.70
1,Cerro do Roque,Janeiro,1.0,01:00:00,2020,11.20,"0,000",20.48,81.50
2,Cerro do Roque,Janeiro,1.0,02:00:00,2020,8.90,"0,000",20.15,83.30
3,Cerro do Roque,Janeiro,1.0,03:00:00,2020,6.30,"0,000",20.24,83.70
4,Cerro do Roque,Janeiro,1.0,04:00:00,2020,8.30,"0,000",20.43,83.70
...,...,...,...,...,...,...,...,...,...
218547,Aroeira,Dezembro,4.0,12:00:00,2023,15.54,"0,00",18.31,58.94
218548,Aroeira,Dezembro,4.0,13:00:00,2023,15.42,"0,00",18.77,56.25
218549,Aroeira,Dezembro,4.0,14:00:00,2023,14.56,"0,00",19.25,52.84
218550,Aroeira,Dezembro,4.0,15:00:00,2023,13.80,"0,00",19.50,51.88
218551,Aroeira,Dezembro,4.0,16:00:00,2023,12.87,"0,00",19.18,52.08

In [66]:
df['Precipitação Total (mm)'] = df['Precipitação Total (mm)'].replace(to_replace=',', value='.', regex=True).astype(float)

In [67]:
df.loc[:, 'nota_temperatura'] = df.apply(lambda x: avaliador_temp(x['Temp. Ar Média (ºC)']), axis=1)
df.loc[:, 'nota_umidade'] = df.apply(lambda x: avaliador_temp(x['Um. Rel. Média (%)']), axis=1)
df.loc[:, 'nota_vento'] = df.apply(lambda x: avaliador_temp(x['Vel, Vento Média (Km/h)']), axis=1)
df.loc[:, 'nota_precipitação'] = df.apply(lambda x: 'Impróprio' if x['Precipitação Total (mm)'] > 0 else 'Ideal', axis=1)

In [ ]:
df

<br> <br>

## Criando função para dar notas aos dados:


> 1 = Pode operar;<br>
> 0 = Não pode operar.

In [68]:
def avaliador(vento, temperatura, umidade, chuva):
  if (vento != "Impróprio" and temperatura != "Impróprio" and umidade != "Impróprio" and chuva == 0):
    return 1
  else:
    return 0

In [69]:
df.loc[:, 'Nota'] = df.apply(lambda x: avaliador(x['nota_vento'],x['nota_temperatura'],
                                                 x['nota_umidade'],
                                                 x['Precipitação Total (mm)']), axis=1)

In [70]:
df.Nota.unique()

array([1, 0], dtype=int64)

In [ ]:
df_only1 = df[df['Nota'] == 1]

In [ ]:
df_only1