# Relatório de An;alise VIII
---
## Importanto Bibliotecas

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('./aluguel_residencial_completo.csv', sep= ';', header= 0)
df.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,42.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,70.00,Casa
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,16.67,Apartamento
4,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,26.00,Apartamento
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0,29.33,Casa
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0,15.38,Casa
7,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,21.43,Apartamento
8,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,16.67,Apartamento
9,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,50.00,Apartamento

In [8]:
selection = df.groupby(df['Tipo'])

In [10]:
selection['Quartos'].describe()

                      count      mean       std  min  25%  50%  75%   max
Tipo
Apartamento         18780.0  2.499095  0.932888  0.0  2.0  2.0  3.0  14.0
Casa                  965.0  3.133679  1.659799  0.0  2.0  3.0  4.0  14.0
Casa de Condomínio    996.0  4.007028  1.185741  1.0  3.0  4.0  5.0  11.0
Casa de Vila          249.0  1.927711  0.956090  0.0  1.0  2.0  2.0   6.0
Quitinete             836.0  0.834928  0.374678  0.0  1.0  1.0  1.0   2.0

In [16]:
rotulos = ['0 a 2 quart0s', '3 a 4 quartos', '4 a 6 quartos', '7 ou mais quartos']

In [18]:
classes = [0, 2, 4, 6, 14]
quartos = pd.cut(
    df['Quartos'],
    bins= classes,
    labels= rotulos
)
quartos.value_counts()

0 a 2 quart0s        11250
3 a 4 quartos         9681
4 a 6 quartos          686
7 ou mais quartos       50
Name: Quartos, dtype: int64

In [13]:
quartos.value_counts()

(0, 2]     11250
(2, 4]      9681
(4, 6]       686
(6, 14]       50
Name: Quartos, dtype: int64